# Generated by Django 4.2.8 on 2024-01-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_order',
            new_name='date_orde',
        ),
    ]
