# Generated by Django 4.2.10 on 2024-02-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_date_order_order_date_orde'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
