# Generated by Django 4.2.10 on 2024-02-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_rename_date_orde_order_date_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItems',
        ),
    ]
