# Generated by Django 4.2.10 on 2024-02-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_orderitem_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
