# Generated by Django 4.2.10 on 2024-02-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitems_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='customer',
        ),
    ]
