# Generated by Django 4.2.10 on 2024-02-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
